### ISSUE TITLE
Cannot build the workspace after checkout of the "feature/lcp" branch

### ISSUE THREAD

**Issue by iurii2017** [readium/SDKLauncher-OSX#50]
The error `error: /Users/iurii_volchyn/Projects/Code/flexo/SDKLauncher-OSX/readium-shared-js/build-output/_multiple-bundles/readium-plugin-highlights.js: No such file or directory" appears while building LaucnherOSX`

#### Expected Behaviour
The build is completed successfully with no errors

#### Observed behaviour
The error listed above while performing the step `PBXCp readium-shared-js/build-output/_multiple-bundles/readium-plugin-highlights.js /Users/iurii_volchyn/Library/Developer/Xcode/DerivedData/LauncherOSX-hffhojdeogpndggexdwkeziupvdx/Build/Products/Debug/LauncherOSX.app/Contents/Resources/Scripts/readium-plugin-highlights.js
    cd /Users/iurii_volchyn/Projects/Code/flexo/SDKLauncher-OSX
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/iurii_volchyn/Projects/Code/flexo/SDKLauncher-OSX/readium-shared-js/build-output/_multiple-bundles/readium-plugin-highlights.js /Users/iurii_volchyn/Library/Developer/Xcode/DerivedData/LauncherOSX-hffhojdeogpndggexdwkeziupvdx/Build/Products/Debug/LauncherOSX.app/Contents/Resources/Scripts`

#### Steps to reproduce
1. Checkout the SDK Launcher for OS X for the branch **feature/lcp** with the submodules
2. Open the `LauncherOSX.xcworkspace` in Xcode and build the app

### Product
* Native application (Readium SDK C++)
  * official "launcher" app for macOS
  * OS Version: Sierra 10.2.6

#### Additional information
I did manage to build both official "launcher" apps for "iOS" and "Android" and the file `readium-plugin-highlights.js` was not required

**Comment by danielweck** [comment]
Fixed in the develop branch:
https://github.com/readium/SDKLauncher-OSX/commit/f0afde8dd2a3a8940f00e018ee09f32026f95967
https://github.com/readium/SDKLauncher-OSX/commit/c0b94ef5425fce8173dfb19e64e7e2bccae8d722

Note that by default, the OSX launcher app uses `reader_RequireJS-multiple-bundles.html` which contains `<script type="text/javascript" src="readium-plugin-highlights.js"> </script>` (and therefore "silently" fails to load the plugin file, since the plugin itself has been removed from the default builds). In order to re-activate the plugin, application developers need to create their own build of `readium-shared-js` by uncommenting the "highlights" entry in the plugins configuration https://github.com/readium/readium-shared-js/blob/master/plugins/plugins.cson#L3
Alternatively, note that using `reader_RequireJS-single-bundle.html` instead of the "multiple bundles" variant means that every built plugin is automatically loaded into the reader instance.

**Comment by danielweck** [comment]
Note that this is fixed in the `feature/lcp` branch too, as it "contains" the `develop` commit history (kept up to date by regularly merging back).

**Comment by iurii2017** [comment]
Hi @danielweck ,

I pulled the changes and was able to build and run the macOS app successfully.
Thanks a lot
<img width="1280" alt="screen shot 2017-10-01 at 18 01 14" src="https://user-images.githubusercontent.com/26297416/31055905-c7f34e16-a6d2-11e7-8159-594db78c7e7f.png">
